### ISSUE TITLE
Add support for P6844

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/nklink#10]
National Library has asked that P6844 (ABART ID Person) be added to NK-link functionalities. They would like to display links to Abart in their records. Is it possible?

**Comment by mormegil-cz** [comment]
Example: https://nklink.toolforge.org/link.php?autid=jk01082370

**Comment by VojtechDostal** [comment]
Can you please add "abart" to supported databases at https://github.com/mormegil-cz/nklink/wiki/N%C3%A1vrh-API ? 
I don't seem to have editing rights. Anyway, thanks for this!
