### ISSUE TITLE
Optionally display Wikidata icon next to value

### ISSUE THREAD

**Issue by VojtechDostal** [mormegil-cz/nklink#11]
National Library has expressed a wish that a small Wikidata icon be displayed next to the value loaded from Wikidata. This way, their frontend would differentiate between values inserted manually and values loaded from Wikidata. Is it possible on our side? I guess it would be relatively easy on their side too, but can we make their life simpler with some easy optional setting (icon=yes sort of thing)?

**Comment by mormegil-cz** [comment]
Maybe I don’t understand the issue: Are we talking about the NKC Aleph page with displayed links, e.g. http://aut.nkp.cz/xx0035515? If so, the layout of the page is totally out of our control. Not only it _could_ be done on their side, it _has to_ be done there; there is nothing we can do to help: nklink only reports a list of all available identifiers+links from Wikidata. Whatever they do with those, how they render them or not (in addition to explicitly stored links or not), that’s all up to them.

But maybe I misunderstood what is requested?

**Comment by VojtechDostal** [comment]
I think You understood it very well. It's only my incomplete understanding of this tool :)

I was worried this could be the case - I wasn't sure what we can "send them". Anyway, even if "sending them an image" was possible, they'd have to configure the access URL to icon=true, in which case it would be probably simpler to just do it on their side completely.

Never mind then :-)
