### ISSUE TITLE
špatné linkování do isni

### ISSUE THREAD

**Issue by carymarydan** [mormegil-cz/nklink#15]
Napr: https://nklink.toolforge.org/link.php?autid=mzk2004222444
V tomto pripade ani link do NK CR neni spravny.

**Comment by mormegil-cz** [comment]
Formát odkazu na ISNI aktualizován, díky za upozornění.

Link do NK ČR u mě vypadá úplně v pořádku, http://aut.nkp.cz/mzk2004222444 (ostatně to je beztak jen opis vstupu).

**Comment by carymarydan** [comment]
Zda se, ze zde je to stále špatně:
https://nklink.toolforge.org/link.php?autid=jn20000604178

**Comment by mormegil-cz** [comment]
Výsledky jsou nacachované, takže jestli někdo navštívil konkrétní stránku nedávno před nasazením opravy, může se zobrazovat ještě ta rozbitá verze. Do 24 hodin by se mělo všechno aktualizovat.
