### ISSUE TITLE
Issue with deprecated rank

### ISSUE THREAD

**Issue by michal-josef-spacek** [mormegil-cz/nklink#8]
There were change of NKČR AUT id (mzk2006324049) to Wikidata.
NKČR AUT id was moved to another QID.
Old one: https://www.wikidata.org/wiki/Q1195453
New one: https://www.wikidata.org/wiki/Q104672509

NKČR AUT id in old one WD item was changed to deprecated value, but nklink still links to this item instead of link to new one item.

As i understand, we need to change query to accept deprecation rank.

**Comment by michal-josef-spacek** [comment]
I prepared PR for fix: https://github.com/mormegil-cz/nklink/pull/9
Tested on https://w.wiki/4Ym3

**Comment by mormegil-cz** [comment]
Closed via #9

**Comment by michal-josef-spacek** [comment]
@mormegil-cz Great, thank you :-)

**Comment by VojtechDostal** [comment]
Hi guys,
I am confused why the link from https://aleph.nkp.cz/F/?func=direct&doc_number=000015162&local_base=AUT still goes to Q106296512. The id at Q106296512 is properly deprecated. Is that a glitch that will solve itself after some time, or did I miss something else there?
thanks

**Comment by michal-josef-spacek** [comment]
@VojtechDostal Everything is fine now :-D

**Comment by mormegil-cz** [comment]
The data is cached for 24 hours, so it should have corrected itself in about 3-hours time. But I purged it from the cache manually, so it is fine now.
